<?php

/** @var  \Magento\Framework\View\Element\Template $block
 */
?>

<div class="custom-slider-block">
    <ul class="custom-slider" data-mage-init='{"Magento_Theme/js/custom-slider": {}}'>
        <li></li>
        <li><img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img2.jpg'); ?>" alt="Image 2" width="250"/></li>
        <li><img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img3.jpg'); ?>" alt="Image 3" width="250"/></li>
        <li><img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img4.jpg'); ?>" alt="Image 4" width="250"/></li>
        <li><img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img5.jpg'); ?>" alt="Image 5" width="250"/></li>
        <li><img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img6.jpg'); ?>" alt="Image 6" width="250"/></li>
    </ul>
</div>

