<?php

/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="product data items tabs-container" data-mage-init='{"Magento_Cms/js/tabs": {}}'>
    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-one">Tab One</a>
    </div>
    <div id="tab-one" class="item content" data-role="content"><?php echo $this->getChildHTML('custom.slider.block'); ?></div>
    <div class="item title" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-two">Tab two</a>
    </div>
    <div id="tab-two" class="item content" data-role="content">
        <button id="button" data-mage-init='{"modal": {}}'>
            <span><?=$escaper->escapeHtml(__('Click me'))?></span>
        </button>
    </div>
</div>
